### ISSUE TITLE
希望支持一下导出pdf,epub格式

### ISSUE THREAD

**Issue by ninjacn** [flyingalex/design-patterns-by-php#8]

**Comment by ZhuPeng** [comment]
推荐一个可以方便的在手机上查看查看这个教程的微信小程序~
![image](https://user-images.githubusercontent.com/4994339/57465030-5c4ef600-72b0-11e9-9f84-3ad0c5f92bb1.png)

小程序是开源的，有任何问题和意见可以直接提 Issue 反馈：[GitHub Trending Hub](https://github.com/ZhuPeng/mp-githubtrending)

**Comment by hulin32** [comment]
@ninjacn 好的，我后面看看

**Comment by hulin32** [comment]
@ninjacn 我弄了一个gitbook, https://hulin.gitbook.io/design-patterns-by-php/, 原来都支持导出pdf，现在好想不行了，没发现什么其他好的工具，如果你想要的话可以试一试这个工具去把gitbook导成pdf, 没用过，不过感觉用起来挺简单的
https://github.com/fuergaosi233/gitbook2pdf

**Comment by ninjacn** [comment]
> @ninjacn 我弄了一个gitbook, https://hulin.gitbook.io/design-patterns-by-php/, 原来都支持导出pdf，现在好想不行了，没发现什么其他好的工具，如果你想要的话可以试一试这个工具去把gitbook导成pdf, 没用过，不过感觉用起来挺简单的
> https://github.com/fuergaosi233/gitbook2pdf

非常感谢，真的很热心😁
